### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by scxwhite** [scxwhite/elasticsearch-hadoop-spark3.0#1]
1. install java 11 (set JAVA_HOME) and java 8 (set JAVA8_HOME)
2. run ./gradlew -DskipTests=true build --info --stacktrace

the build jar path: ./spark/sql-30/build/libs/elasticsearch-spark-30_2.12-8.0.0-SNAPSHOT.jar

**Comment by scxwhite** [comment]
see details : https://github.com/elastic/elasticsearch-hadoop/pull/1498

**Comment by zjd-melo** [comment]
I follow your instructions, got some error, i am not good at java, have any idles?

**Comment by zjd-melo** [comment]
I follow your instructions, got some error, i am not good at java, have any idles?

**Comment by zjd-melo** [comment]
I follow your instructions, got some error, i am not good at java, have any idles?
```/home/hdfs/elasticsearch-hadoop-spark3.0/buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy: 7: unable to resolve class org.elasticsearch.gradle.precommit.UpdateShasTask
 @ line 7, column 1.
   import org.elasticsearch.gradle.precommit.UpdateShasTask
   ^

/home/hdfs/elasticsearch-hadoop-spark3.0/buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy: 5: unable to resolve class org.elasticsearch.gradle.precommit.DependencyLicensesTask
 @ line 5, column 1.
   import org.elasticsearch.gradle.precommit.DependencyLicensesTask
   ^

/home/hdfs/elasticsearch-hadoop-spark3.0/buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy: 6: unable to resolve class org.elasticsearch.gradle.precommit.LicenseHeadersTask
 @ line 6, column 1.
   import org.elasticsearch.gradle.precommit.LicenseHeadersTask
   ^

3 errors

:buildSrc:compileGroovy (Thread[Execution worker for ':buildSrc',5,main]) completed. Took 1.845 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildSrc:compileGroovy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)```
